---
--- Generated by Luanalysis
--- Created by crow.
--- DateTime: 2023/4/12 21:28
---
-- 1.参数列表
-- 1.1 优惠卷id
local voucherId = ARGV[1]
-- 1.2 用户id
local userId = ARGV[2]
-- 1.3 用户id
local orderId = ARGV[3]
-- 2.数据key
local stockKey = 'seckill:stock:' .. voucherId
local orderKey = 'seckill:order:' .. voucherId

-- 3.脚本业务
-- 3.1.判断库存是否充足
if (tonumber(redis.call('get',stockKey)) <= 0) then
    return 1
end
-- 3.2判断是否已经购买
if (redis.call('sismember',orderKey,userId) == 1) then
    --3.3存在
    return 2
end
-- 4.减库存
redis.call('incrby',stockKey,-1)
-- 5.存信息
redis.call('sadd',orderKey,userId)
-- 6.发送消息到队列中
redis.call('xadd','stream.orders','*','userId',userId,'voucherId',voucherId,'id',orderId)

return 0